// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaigonRide.Data;

#nullable disable

namespace SaigonRide.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512115309_AddUserIsLocked")]
    partial class AddUserIsLocked
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaigonRide.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("RentalId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SaigonRide.Models.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("DestinationStationId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalFare")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("StartStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("DestinationStationId");

                    b.HasIndex("StartStationId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("SaigonRide.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentInventory")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("SaigonRide.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("AlertStationInventory")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertStationOverload")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertVehicleMaintenance")
                        .HasColumnType("bit");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPassportVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AlertStationInventory = false,
                            AlertStationOverload = false,
                            AlertVehicleMaintenance = false,
                            Email = "admin@saigonride.vn",
                            FullName = "Thao Nghi Admin",
                            IsLocked = false,
                            IsPassportVerified = false,
                            PasswordHash = "$2a$11$vLe9Wi0Y1ym2JPHaq4qSEeWXxZVpyvyOjCtMkTNXqkfKXzertYd/.",
                            Role = 2,
                            WalletBalance = 0m
                        },
                        new
                        {
                            UserId = 2,
                            AlertStationInventory = false,
                            AlertStationOverload = false,
                            AlertVehicleMaintenance = false,
                            Email = "local@saigonride.vn",
                            FullName = "Nguyen Van A",
                            IsLocked = false,
                            IsPassportVerified = false,
                            PasswordHash = "$2a$11$1K1sJ42.BWDH5dHCarK4dOCkX5Crc9UVGuQaT8gx17TDC5FcZlGL.",
                            Role = 0,
                            WalletBalance = 500000m
                        },
                        new
                        {
                            UserId = 3,
                            AlertStationInventory = false,
                            AlertStationOverload = false,
                            AlertVehicleMaintenance = false,
                            Email = "tourist@saigonride.vn",
                            FullName = "Chris Evans",
                            IsLocked = false,
                            IsPassportVerified = true,
                            PassportNumber = "US123456",
                            PasswordHash = "$2a$11$KF.kKUqRbxDY0ZRV7X68FuD8MDwC6bm0V9upe9QHFumeymF6Sv9ZC",
                            Role = 1,
                            WalletBalance = 1000000m
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StationId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SaigonRide.Models.VehicleCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CategoryId");

                    b.ToTable("VehicleCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Standard Bike",
                            PricePerMinute = 500m
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "E-Scooter",
                            PricePerMinute = 1500m
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.Payment", b =>
                {
                    b.HasOne("SaigonRide.Models.Rental", "Rental")
                        .WithOne("Payment")
                        .HasForeignKey("SaigonRide.Models.Payment", "RentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaigonRide.Models.Rental", b =>
                {
                    b.HasOne("SaigonRide.Models.Station", "DestinationStation")
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SaigonRide.Models.Station", "StartStation")
                        .WithMany()
                        .HasForeignKey("StartStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationStation");

                    b.Navigation("StartStation");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SaigonRide.Models.Vehicle", b =>
                {
                    b.HasOne("SaigonRide.Models.VehicleCategory", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.Station", "Station")
                        .WithMany("Vehicles")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SaigonRide.Models.Rental", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SaigonRide.Models.Station", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SaigonRide.Models.User", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("SaigonRide.Models.Vehicle", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("SaigonRide.Models.VehicleCategory", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
