// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaigonRide.Data;

#nullable disable

namespace SaigonRide.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaigonRide.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("RentalId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SaigonRide.Models.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("DestinationStationId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalFare")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("StartStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("DestinationStationId");

                    b.HasIndex("StartStationId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("SaigonRide.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentInventory")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 1,
                            Capacity = 50,
                            CurrentInventory = 25,
                            Location = "District 1",
                            StationName = "Ben Thanh Market",
                            Status = "Active"
                        },
                        new
                        {
                            StationId = 2,
                            Capacity = 45,
                            CurrentInventory = 11,
                            Location = "District 1",
                            StationName = "Nguyen Hue Walking St",
                            Status = "Active"
                        },
                        new
                        {
                            StationId = 3,
                            Capacity = 25,
                            CurrentInventory = 1,
                            Location = "Binh Thanh District",
                            StationName = "Landmark 81",
                            Status = "Active"
                        },
                        new
                        {
                            StationId = 4,
                            Capacity = 40,
                            CurrentInventory = 7,
                            Location = "District 7",
                            StationName = "Tan Hung",
                            Status = "Active"
                        },
                        new
                        {
                            StationId = 5,
                            Capacity = 30,
                            CurrentInventory = 2,
                            Location = "Phu Nhuan District",
                            StationName = "Phu Nhuan Station",
                            Status = "Active"
                        },
                        new
                        {
                            StationId = 6,
                            Capacity = 50,
                            CurrentInventory = 48,
                            Location = "Thu Duc City",
                            StationName = "Thu Duc Station",
                            Status = "Active"
                        },
                        new
                        {
                            StationId = 7,
                            Capacity = 20,
                            CurrentInventory = 10,
                            Location = "District 1",
                            StationName = "Bui Vien Street",
                            Status = "Active"
                        },
                        new
                        {
                            StationId = 8,
                            Capacity = 35,
                            CurrentInventory = 20,
                            Location = "District 3",
                            StationName = "Notre-Dame Cathedral",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPassportVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@saigonride.vn",
                            FullName = "Thao Nghi Admin",
                            IsPassportVerified = false,
                            PasswordHash = "$2a$11$vA8oUo.hP36376FYrWBcSe2Pe6/Lh/KLXLUPEDIOgtpvS7ErgfQgC",
                            Role = 2,
                            WalletBalance = 0m
                        },
                        new
                        {
                            UserId = 2,
                            Email = "local@saigonride.vn",
                            FullName = "Nguyen Van A",
                            IsPassportVerified = false,
                            PasswordHash = "$2a$11$kcXB79TmzsSLsyPaSoKteeLAax2w1OdcOHsmvpXo5plVrKR9W4ycG",
                            Role = 0,
                            WalletBalance = 500000m
                        },
                        new
                        {
                            UserId = 3,
                            Email = "tourist@saigonride.vn",
                            FullName = "Chris Evans",
                            IsPassportVerified = true,
                            PassportNumber = "US123456",
                            PasswordHash = "$2a$11$gBZWcMkRztGQm...KPZohu/Nw4BvubfHEp2GdQS.7upepKxZfwHM6",
                            Role = 1,
                            WalletBalance = 1000000m
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StationId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            CategoryId = 1,
                            StationId = 1,
                            Status = 0,
                            VehicleCode = "SB-V3-0017",
                            VehicleName = "Bike VN-01"
                        },
                        new
                        {
                            VehicleId = 2,
                            CategoryId = 2,
                            StationId = 4,
                            Status = 1,
                            VehicleCode = "ES-F4-0042",
                            VehicleName = "E-Scooter CT-01"
                        },
                        new
                        {
                            VehicleId = 3,
                            CategoryId = 1,
                            StationId = 2,
                            Status = 2,
                            VehicleCode = "ES-A1-0079",
                            VehicleName = "Bike AG-01"
                        },
                        new
                        {
                            VehicleId = 4,
                            CategoryId = 2,
                            StationId = 3,
                            Status = 2,
                            VehicleCode = "SB-M1-001",
                            VehicleName = "E-Scooter CM-01"
                        },
                        new
                        {
                            VehicleId = 5,
                            CategoryId = 1,
                            StationId = 4,
                            Status = 1,
                            VehicleCode = "SB-NS-0339",
                            VehicleName = "Bike TN-01"
                        },
                        new
                        {
                            VehicleId = 6,
                            CategoryId = 2,
                            StationId = 5,
                            Status = 1,
                            VehicleCode = "ES-E7-8386",
                            VehicleName = "E-Scooter DB-01"
                        },
                        new
                        {
                            VehicleId = 7,
                            CategoryId = 1,
                            StationId = 7,
                            Status = 0,
                            VehicleCode = "SB-T9-0099",
                            VehicleName = "Bike TW-01"
                        },
                        new
                        {
                            VehicleId = 8,
                            CategoryId = 2,
                            StationId = 1,
                            Status = 0,
                            VehicleCode = "ES-D2-0011",
                            VehicleName = "E-Scooter VN-01"
                        },
                        new
                        {
                            VehicleId = 9,
                            CategoryId = 1,
                            StationId = 7,
                            Status = 0,
                            VehicleCode = "SB-K1-0055",
                            VehicleName = "Bike BV-01"
                        },
                        new
                        {
                            VehicleId = 10,
                            CategoryId = 2,
                            StationId = 8,
                            Status = 0,
                            VehicleCode = "ES-L3-0088",
                            VehicleName = "E-Scooter ND-01"
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.VehicleCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CategoryId");

                    b.ToTable("VehicleCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Standard Bike",
                            PricePerMinute = 500m
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "E-Scooter",
                            PricePerMinute = 1500m
                        });
                });

            modelBuilder.Entity("SaigonRide.Models.Payment", b =>
                {
                    b.HasOne("SaigonRide.Models.Rental", "Rental")
                        .WithOne("Payment")
                        .HasForeignKey("SaigonRide.Models.Payment", "RentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaigonRide.Models.Rental", b =>
                {
                    b.HasOne("SaigonRide.Models.Station", "DestinationStation")
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SaigonRide.Models.Station", "StartStation")
                        .WithMany()
                        .HasForeignKey("StartStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationStation");

                    b.Navigation("StartStation");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SaigonRide.Models.Vehicle", b =>
                {
                    b.HasOne("SaigonRide.Models.VehicleCategory", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaigonRide.Models.Station", "Station")
                        .WithMany("Vehicles")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SaigonRide.Models.Rental", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SaigonRide.Models.Station", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SaigonRide.Models.User", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("SaigonRide.Models.Vehicle", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("SaigonRide.Models.VehicleCategory", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
